// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6x7rqTosz5ny_i5gg8stmyRostPvUlU',
    appId: '1:1055896186316:web:266a521d5956424a634169',
    messagingSenderId: '1055896186316',
    projectId: 'youtvplay-ae0f7',
    authDomain: 'youtvplay-ae0f7.firebaseapp.com',
    storageBucket: 'youtvplay-ae0f7.firebasestorage.app',
    measurementId: 'G-0FFKV329N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzCsIHTKSNCzHW--hdi9aXrH7hgqRZXs',
    appId: '1:1055896186316:android:d3eccf3e6021fb12634169',
    messagingSenderId: '1055896186316',
    projectId: 'youtvplay-ae0f7',
    storageBucket: 'youtvplay-ae0f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9Ci_seipGiMItvixEWZ25lYPwVdZTXA',
    appId: '1:1055896186316:ios:bc4c462e5f118c2c634169',
    messagingSenderId: '1055896186316',
    projectId: 'youtvplay-ae0f7',
    storageBucket: 'youtvplay-ae0f7.firebasestorage.app',
    iosBundleId: 'com.example.tajamarTvPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB9Ci_seipGiMItvixEWZ25lYPwVdZTXA',
    appId: '1:1055896186316:ios:bc4c462e5f118c2c634169',
    messagingSenderId: '1055896186316',
    projectId: 'youtvplay-ae0f7',
    storageBucket: 'youtvplay-ae0f7.firebasestorage.app',
    iosBundleId: 'com.example.tajamarTvPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP6x7rqTosz5ny_i5gg8stmyRostPvUlU',
    appId: '1:1055896186316:web:22449c53aecf053c634169',
    messagingSenderId: '1055896186316',
    projectId: 'youtvplay-ae0f7',
    authDomain: 'youtvplay-ae0f7.firebaseapp.com',
    storageBucket: 'youtvplay-ae0f7.firebasestorage.app',
    measurementId: 'G-7TD78SDXSG',
  );
}
