import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../domain/entities/channel_entity.dart';
import '../providers/channel_admin_provider.dart';

class AddChannelDialog extends ConsumerStatefulWidget {
  const AddChannelDialog({super.key});

  @override
  ConsumerState<AddChannelDialog> createState() => _AddChannelDialogState();
}

class _AddChannelDialogState extends ConsumerState<AddChannelDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _urlController = TextEditingController();
  final _logoController = TextEditingController();
  String _categoryId = 'General';
  String _streamType = 'hls';

  @override
  void dispose() {
    _nameController.dispose();
    _urlController.dispose();
    _logoController.dispose();
    super.dispose();
  }

  void _submit() {
    if (_formKey.currentState!.validate()) {
      final newChannel = ChannelEntity(
        id: '', // Generated by Firestore
        companyId: 'company_tajamar', // Default for now
        name: _nameController.text.trim(),
        logo: _logoController.text.trim().isNotEmpty ? _logoController.text.trim() : 'https://via.placeholder.com/150',
        categoryId: _categoryId,
        url: _urlController.text.trim(),
        streamType: _streamType,
        language: 'es',
        country: 'AR',
        epgId: '',
        status: 'online',
      );

      ref.read(channelAdminControllerProvider.notifier).addChannel(newChannel);
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Añadir Nuevo Canal'),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Nombre del Canal *'),
                validator: (val) => val == null || val.isEmpty ? 'Requerido' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _urlController,
                decoration: const InputDecoration(labelText: 'URL del Stream *'),
                validator: (val) => val == null || val.isEmpty ? 'Requerido' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _logoController,
                decoration: const InputDecoration(labelText: 'URL del Logo (Opcional)'),
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _categoryId,
                decoration: const InputDecoration(labelText: 'Categoría'),
                items: ['General', 'Deportes', 'Noticias', 'Cine', 'Infantil']
                    .map((cat) => DropdownMenuItem(value: cat, child: Text(cat)))
                    .toList(),
                onChanged: (val) {
                  if (val != null) setState(() => _categoryId = val);
                },
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _streamType,
                decoration: const InputDecoration(labelText: 'Tipo de Stream'),
                items: ['hls', 'dash', 'rtmp', 'mp4', 'youtube']
                    .map((type) => DropdownMenuItem(value: type, child: Text(type.toUpperCase())))
                    .toList(),
                onChanged: (val) {
                  if (val != null) setState(() => _streamType = val);
                },
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancelar'),
        ),
        ElevatedButton(
          onPressed: _submit,
          child: const Text('Guardar Canal'),
        ),
      ],
    );
  }
}
